import { useState, useEffect, useRef } from 'react';
import { router } from '@inertiajs/react';
import { XMarkIcon, PaperClipIcon, TrashIcon } from '@heroicons/react/24/outline';
import EmailStatusTracker from './EmailStatusTracker';
import './AddDocumentModal.css';

export default function AddDocumentModal({ isOpen, onClose, onSubmit }) {
    // Form state
    const [formData, setFormData] = useState({
        tracking_number: '', // Will be auto-generated by backend
        title: '',
        type: '',
        origin_type: '',
        last_transaction: '',
        first_name: '',
        fullname: '',
        division_code: '',
        division: '',
        date_received: '',
        status: 'Pending',
        urgency: 'medium',
        description: '',
        assigned_to: '',
        department: '',
        remarks: '',
        file: null, // For file upload
        recipients: [] // Array of recipients
    });

    const [errors, setErrors] = useState({});
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [showSuccess, setShowSuccess] = useState(false);
    const [submittedDocument, setSubmittedDocument] = useState(null);
    const [recipientInput, setRecipientInput] = useState({ name: '', email: '' });
    const [recipientSearch, setRecipientSearch] = useState('');
    const [recipientDropdownOpen, setRecipientDropdownOpen] = useState(false);
    const fileInputRef = useRef(null);
    const [fileName, setFileName] = useState('');
    const [employees, setEmployees] = useState([]);
    const [employeesLoading, setEmployeesLoading] = useState(false);
    const [employeeError, setEmployeeError] = useState('');
    const [employeeSearch, setEmployeeSearch] = useState('');
    const [employeeDropdownOpen, setEmployeeDropdownOpen] = useState(false);
    

    
  

    // Log when modal opens
    useEffect(() => {
        if (isOpen) {
            console.log('📂 Add Document Modal Opened');
            console.log('Initial form data:', formData);
        }
    }, [isOpen]);

    useEffect(() => {
        if (!isOpen) return;

        setEmployeesLoading(true);
        setEmployeeError('');
        fetch('/api/employees', { headers: { Accept: 'application/json' } })
            .then(response => {
                if (!response.ok) throw new Error('Unable to load employees');
                return response.json();
            })
            .then(payload => setEmployees(payload.employees || []))
            .catch(error => setEmployeeError(error.message))
            .finally(() => setEmployeesLoading(false));
    }, [isOpen]);

    // Handle input changes with logging
    const handleChange = (e) => {
        const { name, value, type, checked } = e.target;
        const newValue = type === 'checkbox' ? checked : value;
        
        console.log(`🔄 Field changed: ${name}`);
        console.log(`   Old value: ${formData[name]}`);
        console.log(`   New value: ${newValue}`);
        
        setFormData(prev => {
            const updated = { ...prev, [name]: newValue };
            console.log('📝 Updated form state:', updated);
            return updated;
        });

        // Clear error for this field if exists
        if (errors[name]) {
            setErrors(prev => ({ ...prev, [name]: '' }));
        }
    };

    // Handle file upload
    const handleFileChange = (e) => {
        const file = e.target.files[0];
        console.log('📎 File selected:', file);
        console.log('   File name:', file?.name);
        console.log('   File size:', file?.size, 'bytes');
        console.log('   File type:', file?.type);
        
        setFormData(prev => ({ ...prev, file }));
        setFileName(file?.name || '');
    };

    // Add recipient
    const addRecipient = () => {
        console.log('👤 Adding recipient:', recipientInput);
        
        if (!recipientInput.name.trim() || !recipientInput.email.trim()) {
            console.warn('⚠️ Recipient name and email are required');
            alert('Please enter both name and email for the recipient');
            return;
        }

        // Validate email format
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(recipientInput.email)) {
            console.warn('⚠️ Invalid email format:', recipientInput.email);
            alert('Please enter a valid email address');
            return;
        }

        const newRecipient = {
            name: recipientInput.name.trim(),
            email: recipientInput.email.trim(),
            first_name: recipientInput.first_name || formData.first_name,
            last_name: recipientInput.last_name || '',
            fullname: recipientInput.fullname || formData.fullname,
            division_code: recipientInput.division_code || formData.division_code,
            division: recipientInput.division || formData.division,
        };

        setFormData(prev => {
            const updated = {
                ...prev,
                recipients: [...prev.recipients, newRecipient]
            };
            console.log('📋 Updated recipients:', updated.recipients);
            return updated;
        });

        // Clear recipient input
        setRecipientInput({ name: '', email: '' });
        setRecipientSearch('');
        setRecipientDropdownOpen(false);
    };

    // Remove recipient
    const removeRecipient = (index) => {
        console.log(`🗑️ Removing recipient at index ${index}`);
        console.log('   Recipient:', formData.recipients[index]);
        
        setFormData(prev => {
            const updated = {
                ...prev,
                recipients: prev.recipients.filter((_, i) => i !== index)
            };
            console.log('📋 Updated recipients after removal:', updated.recipients);
            return updated;
        });
    };

    // Log all form data on demand (for debugging)
    const logCurrentFormData = () => {
        console.group('📊 Current Form Data');
        console.log('Full form data:', formData);
        console.log('Form data as JSON:', JSON.stringify({
            ...formData,
            file: formData.file ? formData.file.name : null,
            recipients: formData.recipients
        }, null, 2));
        console.log('Individual fields:');
        Object.entries(formData).forEach(([key, value]) => {
            if (key === 'file') {
                console.log(`  ${key}:`, value ? value.name : null);
            } else if (key === 'recipients') {
                console.log(`  ${key}:`, value, `(${value.length} recipients)`);
            } else {
                console.log(`  ${key}:`, value, `(${typeof value})`);
            }
        });
        console.log('Total fields:', Object.keys(formData).length);
        console.groupEnd();
    };

    // Validate form
    const validateForm = () => {
        const newErrors = {};
        
        if (!formData.title.trim()) {
            newErrors.title = 'Document title is required';
        }
        if (!formData.type) {
            newErrors.type = 'Document type is required';
        }
        if (!formData.origin_type) {
            newErrors.origin_type = 'Origin type is required';
        }
        if (!formData.date_received) {
            newErrors.date_received = 'Date received is required';
        }
        if (!formData.status) {
            newErrors.status = 'Status is required';
        }
        if (!formData.urgency) {
            newErrors.urgency = 'Urgency level is required';
        }
        if (formData.recipients.length === 0) {
            newErrors.recipients = 'At least one recipient is required';
        }

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    // Handle form submission with comprehensive logging
    const handleSubmit = (e) => {
        e.preventDefault();
        
        console.group('📤 FORM SUBMISSION STARTED');
        console.log('🕐 Timestamp:', new Date().toISOString());
        console.log('📋 Form data before validation:', {
            ...formData,
            file: formData.file ? formData.file.name : null
        });
        
        // Log all form data in detail
        console.log('🔍 Detailed form data:');
        Object.entries(formData).forEach(([key, value]) => {
            if (key === 'file') {
                console.log(`   ${key}:`, value ? {
                    name: value.name,
                    size: value.size,
                    type: value.type
                } : null);
            } else if (key === 'recipients') {
                console.log(`   ${key}:`, value, `(${value.length} recipients)`);
                value.forEach((r, i) => {
                    console.log(`     Recipient ${i + 1}:`, r);
                });
            } else {
                console.log(`   ${key}:`, value, `(${typeof value})`);
            }
        });

        // Validate form
        const isValid = validateForm();
        console.log('✅ Validation result:', isValid);
        
        if (!isValid) {
            console.error('❌ Form validation failed!');
            console.log('🚫 Validation errors:', errors);
            console.groupEnd();
            return;
        }

        console.log('✅ Form validation passed!');
        
        // Prepare data for submission (matches backend expectations)
        const submitData = {
            title: formData.title,
            type: formData.type,
            origin_type: formData.origin_type,
            last_transaction: formData.last_transaction,
            first_name: formData.first_name,
            fullname: formData.fullname,
            division_code: formData.division_code,
            division: formData.division,
            date_received: formData.date_received,
            status: formData.status,
            urgency: formData.urgency,
            description: formData.description,
            assigned_to: formData.assigned_to,
            department: formData.department,
            remarks: formData.remarks,
            recipients: formData.recipients
        };

        // Log what's being submitted
        console.log('📦 Data to be submitted:', {
            ...submitData,
            file: formData.file ? formData.file.name : null,
            recipients: submitData.recipients
        });
        
        // Create FormData for file upload
        const formDataToSend = new FormData();

        // Append all text fields. Use nested recipient keys so Laravel can parse them as an array
        Object.keys(submitData).forEach(key => {
            if (key === 'recipients') {
                submitData.recipients.forEach((recipient, index) => {
                    formDataToSend.append(`recipients[${index}][name]`, recipient.name);
                    formDataToSend.append(`recipients[${index}][email]`, recipient.email);
                    console.log(`📤 Appending recipient ${index}:`, recipient);
                });
            } else if (submitData[key] !== null && submitData[key] !== undefined) {
                formDataToSend.append(key, submitData[key]);
                console.log(`📤 Appending ${key}:`, submitData[key]);
            }
        });

        // Append file if exists
        if (formData.file) {
            formDataToSend.append('file', formData.file);
            console.log(`📤 Appending file:`, formData.file.name);
        }

        // Call parent handler
        if (onSubmit) {
            console.log('📞 Calling parent onSubmit handler...');
            onSubmit(submitData);
        }

        // Set submitting state
        setIsSubmitting(true);
        console.log('⏳ Submitting form...');

        // Log the request configuration
        console.log('🌐 Sending POST request to: /documents');
        console.log('📤 Request content-type: multipart/form-data');
        console.log('📤 FormData entries:');
        for (let [key, value] of formDataToSend.entries()) {
            if (key === 'file') {
                console.log(`   ${key}: ${value.name} (${value.size} bytes)`);
            } else {
                console.log(`   ${key}: ${value}`);
            }
        }

        // Submit via Inertia
        router.post('/documents', formDataToSend, {
            preserveState: true,
            preserveScroll: true,
            onStart: () => {
                console.log('🔄 Request started...');
            },
            onProgress: (progress) => {
                console.log('📊 Upload progress:', progress);
            },
            onSuccess: (response) => {
                console.log('✅ Document created successfully!');
                console.log('📥 Server response:', response);
                console.log('🎯 Success data:', response.props);
                
                setIsSubmitting(false);
                setShowSuccess(true);
                setSubmittedDocument(response.props?.document || null);
                
                // Log success details
                console.log('📋 Success details:');
                if (response.props?.document) {
                    console.log('   Document ID:', response.props.document.id);
                    console.log('   Document Title:', response.props.document.title);
                    console.log('   Tracking Number:', response.props.document.tracking_number);
                    console.log('   Recipients:', response.props.document.recipients?.length || 0);
                }
                
                setTimeout(() => {
                    setShowSuccess(false);
                    resetForm();
                    console.log('🔚 Closing modal and redirecting to documents index...');
                    onClose();
                    router.visit('/documents', {
                        preserveScroll: true,
                        preserveState: false,
                    });
                }, 2000);
                console.groupEnd();
            },
            onError: (errors) => {
                console.error('❌ Submission failed!');
                console.error('🚫 Validation errors from server:', errors);
                console.log('📋 Error details:', JSON.stringify(errors, null, 2));
                
                // Map server errors to fields
                const formattedErrors = {};
                Object.entries(errors).forEach(([key, value]) => {
                    formattedErrors[key] = value;
                    console.log(`   ${key}: ${value}`);
                });
                
                setErrors(formattedErrors);
                setIsSubmitting(false);
                console.groupEnd();
            },
            onFinish: () => {
                console.log('🏁 Request completed (success or error)');
                setIsSubmitting(false);
            },
        });
    };

    // Reset form
    const resetForm = () => {
        console.log('🔄 Resetting form...');
        setFormData({
            tracking_number: '',
            title: '',
            type: '',
            origin_type: '',
            last_transaction: '',
            first_name: '',
            fullname: '',
            division_code: '',
            division: '',
            date_received: '',
            status: 'Pending',
            urgency: 'medium',
            description: '',
            assigned_to: '',
            department: '',
            remarks: '',
            file: null,
            recipients: []
        });
        setFileName('');
        setRecipientInput({ name: '', email: '' });
        setEmployeeSearch('');
        setEmployeeDropdownOpen(false);
        setRecipientSearch('');
        setRecipientDropdownOpen(false);
        setErrors({});
        if (fileInputRef.current) {
            fileInputRef.current.value = '';
        }
        console.log('✅ Form reset complete');
    };

    const selectEmployee = (employeeId) => {
        const employee = employees.find(item => String(item.id) === String(employeeId));
        setEmployeeSearch(employee?.first_name || '');
        setEmployeeDropdownOpen(false);
        setFormData(prev => ({
            ...prev,
            fullname: employee?.fullname || '',
            first_name: employee?.first_name || '',
            assigned_to: employee?.fullname || '',
            division_code: employee?.division_code || '',
            division: employee?.division || '',
            department: employee?.division || '',
        }));
        if (employee) {
            setRecipientInput(prev => ({
                ...prev,
                name: employee.fullname || '',
                email: employee.email || '',
            }));
        }
    };

    const filteredEmployees = employees.filter(employee => {
        const search = employeeSearch.trim().toLowerCase();
        return !search
            || employee.first_name?.toLowerCase().includes(search)
            || employee.fullname?.toLowerCase().includes(search);
    });

    const filteredRecipientEmployees = employees.filter(employee => {
        const search = recipientSearch.trim().toLowerCase();
        return !search
            || employee.last_name?.toLowerCase().includes(search)
            || employee.fullname?.toLowerCase().includes(search);
    });

    const selectRecipient = (employeeId) => {
        const employee = employees.find(item => String(item.id) === String(employeeId));
        setRecipientSearch(employee?.last_name || '');
        setRecipientDropdownOpen(false);
        setRecipientInput({
            name: employee?.fullname || '',
            email: employee?.email || '',
            first_name: employee?.first_name || '',
            last_name: employee?.last_name || '',
            fullname: employee?.fullname || '',
            division_code: employee?.division_code || '',
            division: employee?.division || '',
        });
    };

    // Handle modal close
    const handleClose = () => {
        console.log('❌ Modal closing...');
        if (isSubmitting) {
            console.log('⏳ Submission in progress, cannot close');
            return;
        }
        resetForm();
        onClose();
        console.log('✅ Modal closed successfully');
    };

    // If modal is not open, return null
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 overflow-y-auto">
            <div className="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
                {/* Background overlay */}
                <div 
                    className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
                    onClick={handleClose}
                ></div>

                {/* Modal panel */}
                <div className="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-4xl sm:w-full">
                    {/* Modal header */}
                    <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
                        <div>
                            <h3 className="text-lg font-semibold text-gray-900">Add New Document</h3>
                            <p className="text-sm text-gray-500">Fill in the document details below</p>
                        </div>
                        <button
                            onClick={handleClose}
                            className="text-gray-400 hover:text-gray-500"
                            disabled={isSubmitting}
                        >
                            <XMarkIcon className="w-6 h-6" />
                        </button>
                    </div>

                    {/* Form */}
                    <form onSubmit={handleSubmit} className="px-6 py-4">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            {/* Document Title */}
                            <div className="col-span-1 md:col-span-2">
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Document Title <span className="text-red-500">*</span>
                                </label>
                                <input
                                    type="text"
                                    name="title"
                                    value={formData.title}
                                    onChange={handleChange}
                                    className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                                        errors.title ? 'border-red-500' : 'border-gray-300'
                                    }`}
                                    placeholder="Enter document title"
                                    disabled={isSubmitting}
                                />
                                {errors.title && (
                                    <p className="mt-1 text-sm text-red-500">{errors.title}</p>
                                )}
                            </div>

                            {/* Document Type */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Document Type <span className="text-red-500">*</span>
                                </label>
                                <select
                                    name="type"
                                    value={formData.type}
                                    onChange={handleChange}
                                    className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                                        errors.type ? 'border-red-500' : 'border-gray-300'
                                    }`}
                                    disabled={isSubmitting}
                                >
                                    <option value="">Select type</option>
                                    <option value="memo">Memo</option>
                                    <option value="letter">Letter</option>
                                    <option value="report">Report</option>
                                    <option value="invoice">Invoice</option>
                                    <option value="contract">Contract</option>
                                    <option value="proposal">Proposal</option>
                                    <option value="other">Other</option>
                                </select>
                                {errors.type && (
                                    <p className="mt-1 text-sm text-red-500">{errors.type}</p>
                                )}
                            </div>

                            {/* Date Received */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Origin Type <span className="text-red-500">*</span>
                                </label>
                                <select
                                    name="origin_type"
                                    value={formData.origin_type}
                                    onChange={handleChange}
                                    className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                                        errors.origin_type ? 'border-red-500' : 'border-gray-300'
                                    }`}
                                    disabled={isSubmitting}
                                >
                                    <option value="">Select origin type</option>
                                    <option value="Internal">Internal</option>
                                    <option value="External">External</option>
                                    <option value="Walk-in">Walk-in</option>
                                    <option value="Email">Email</option>
                                    <option value="Other">Other</option>
                                </select>
                                {errors.origin_type && (
                                    <p className="mt-1 text-sm text-red-500">{errors.origin_type}</p>
                                )}
                            </div>

                            {/* Date Received */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Date Received <span className="text-red-500">*</span>
                                </label>
                                <input
                                    type="date"
                                    name="date_received"
                                    value={formData.date_received}
                                    onChange={handleChange}
                                    className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                                        errors.date_received ? 'border-red-500' : 'border-gray-300'
                                    }`}
                                    disabled={isSubmitting}
                                />
                                {errors.date_received && (
                                    <p className="mt-1 text-sm text-red-500">{errors.date_received}</p>
                                )}
                            </div>

                            {/* Last Transaction */}
                            <div className="col-span-1 md:col-span-2">
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Last Transaction
                                </label>
                                <input
                                    type="text"
                                    name="last_transaction"
                                    value={formData.last_transaction}
                                    onChange={handleChange}
                                    className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                                        errors.last_transaction ? 'border-red-500' : 'border-gray-300'
                                    }`}
                                    placeholder="Enter the latest document transaction"
                                    disabled={isSubmitting}
                                />
                                {errors.last_transaction && (
                                    <p className="mt-1 text-sm text-red-500">{errors.last_transaction}</p>
                                )}
                            </div>

                            {/* Status */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Status <span className="text-red-500">*</span>
                                </label>
                                <select
                                    name="status"
                                    value={formData.status}
                                    onChange={handleChange}
                                    className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                                        errors.status ? 'border-red-500' : 'border-gray-300'
                                    }`}
                                    disabled={isSubmitting}
                                >
                                    <option value="Pending">Pending</option>
                                    <option value="Processing">Processing</option>
                                    <option value="Reviewed">Reviewed</option>
                                    <option value="Approved">Approved</option>
                                    <option value="Rejected">Rejected</option>
                                    <option value="Archived">Archived</option>
                                </select>
                                {errors.status && (
                                    <p className="mt-1 text-sm text-red-500">{errors.status}</p>
                                )}
                            </div>

                            {/* Urgency */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Urgency Level <span className="text-red-500">*</span>
                                </label>
                                <select
                                    name="urgency"
                                    value={formData.urgency}
                                    onChange={handleChange}
                                    className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                                        errors.urgency ? 'border-red-500' : 'border-gray-300'
                                    }`}
                                    disabled={isSubmitting}
                                >
                                    <option value="low">Low</option>
                                    <option value="medium">Medium</option>
                                    <option value="high">High</option>
                                    <option value="critical">Critical</option>
                                </select>
                                {errors.urgency && (
                                    <p className="mt-1 text-sm text-red-500">{errors.urgency}</p>
                                )}
                            </div>

                            {/* Assigned To */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    First Name
                                </label>
                                <div className="employee-combobox">
                                    <input
                                        type="search"
                                        value={employeeSearch}
                                        onFocus={() => setEmployeeDropdownOpen(true)}
                                        onChange={(e) => {
                                            setEmployeeSearch(e.target.value);
                                            setEmployeeDropdownOpen(true);
                                        }}
                                        className="employee-select w-full px-3 py-2 border border-gray-300 rounded-md"
                                        placeholder={employeesLoading ? 'Loading employees...' : 'Search first name'}
                                        disabled={isSubmitting || employeesLoading}
                                        autoComplete="off"
                                    />
                                    {employeeDropdownOpen && !employeesLoading && employeeSearch && filteredEmployees.length > 0 && (
                                        <div className="employee-options" role="listbox">
                                            {filteredEmployees.slice(0, 20).map(employee => (
                                                <button
                                                    type="button"
                                                    key={`${employee.id}-${employee.email}`}
                                                    className="employee-option"
                                                    onMouseDown={(event) => event.preventDefault()}
                                                    onClick={() => selectEmployee(employee.id)}
                                                >
                                                    <span>{employee.first_name || employee.fullname}</span>
                                                    <small>{employee.fullname}</small>
                                                </button>
                                            ))}
                                        </div>
                                    )}
                                </div>
                                {employeeError && <p className="mt-1 text-sm text-red-500">{employeeError}</p>}
                            </div>

                            {/* Assigned To */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Assigned To
                                </label>
                                <input
                                    type="text"
                                    name="assigned_to"
                                    value={formData.assigned_to}
                                    readOnly
                                    className="employee-field w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                                    placeholder="Selected employee fullname"
                                    disabled={isSubmitting}
                                />
                            </div>

                            

                            {/* Department */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Department
                                </label>
                                <input
                                    type="text"
                                    name="department"
                                    value={formData.department}
                                    readOnly
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                                    placeholder="Selected employee division"
                                    disabled={isSubmitting}
                                />
                            </div>

                           

                            

                            {/* File Upload */}
                            <div className="col-span-1 md:col-span-2">
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Upload File
                                </label>
                                <div className="flex items-center space-x-3">
                                    <input
                                        ref={fileInputRef}
                                        type="file"
                                        onChange={handleFileChange}
                                        className="hidden"
                                        id="file-upload"
                                        disabled={isSubmitting}
                                    />
                                    <label
                                        htmlFor="file-upload"
                                        className="cursor-pointer inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50"
                                    >
                                        <PaperClipIcon className="w-4 h-4 mr-2" />
                                        Choose File
                                    </label>
                                    {fileName && (
                                        <span className="text-sm text-gray-600">
                                            {fileName}
                                        </span>
                                    )}
                                </div>
                            </div>

                            {/* Recipients Section */}
                            <div className="col-span-1 md:col-span-2">
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Recipients <span className="text-red-500">*</span>
                                </label>
                                
                                {/* Add Recipient */}
                                <div className="flex flex-wrap gap-2 mb-3">
                                    <div className="employee-combobox flex-1 min-w-[200px]">
                                        <input
                                            type="search"
                                            value={recipientSearch}
                                            onFocus={() => setRecipientDropdownOpen(true)}
                                            onChange={(e) => {
                                                setRecipientSearch(e.target.value);
                                                setRecipientDropdownOpen(true);
                                            }}
                                            className="employee-select w-full px-3 py-2 border border-gray-300 rounded-md"
                                            placeholder="Search recipient last name"
                                            disabled={isSubmitting || employeesLoading}
                                            autoComplete="off"
                                        />
                                        {recipientDropdownOpen && !employeesLoading && recipientSearch && filteredRecipientEmployees.length > 0 && (
                                            <div className="employee-options" role="listbox">
                                                {filteredRecipientEmployees.slice(0, 20).map(employee => (
                                                    <button
                                                        type="button"
                                                        key={`recipient-${employee.id}-${employee.email}`}
                                                        className="employee-option"
                                                        onMouseDown={(event) => event.preventDefault()}
                                                        onClick={() => selectRecipient(employee.id)}
                                                    >
                                                        <span>{employee.last_name || employee.fullname}</span>
                                                        <small>{employee.fullname}</small>
                                                    </button>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                    <input
                                        type="email"
                                        placeholder="Recipient Email"
                                        value={recipientInput.email}
                                        onChange={(e) => setRecipientInput(prev => ({ ...prev, email: e.target.value }))}
                                        className="flex-1 min-w-[200px] px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                                        disabled={isSubmitting}
                                    />
                                    <button
                                        type="button"
                                        onClick={addRecipient}
                                        className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700"
                                        disabled={isSubmitting}
                                    >
                                        Add
                                    </button>
                                </div>

                                {/* Recipients List */}
                                {formData.recipients.length > 0 && (
                                    <div className="mt-2">
                                        <p className="text-sm text-gray-600 mb-2">
                                            {formData.recipients.length} recipient(s) added
                                        </p>
                                        <div className="space-y-2">
                                            {formData.recipients.map((recipient, index) => (
                                                <div key={index} className="flex items-center justify-between bg-gray-50 px-3 py-2 rounded-md">
                                                    <div>
                                                        {recipient.first_name && (
                                                            <span className="mr-2 text-gray-600">First name: {recipient.first_name}</span>
                                                        )}
                                                        {recipient.last_name && (
                                                            <span className="mr-2 text-gray-600">Last name: {recipient.last_name}</span>
                                                        )}
                                                        <span className="font-medium">{recipient.fullname || recipient.name}</span>
                                                        {recipient.division && <span className="ml-2 text-gray-500">({recipient.division})</span>}
                                                        <span className="mx-2 text-gray-400">|</span>
                                                        <span className="text-gray-600">{recipient.email}</span>
                                                    </div>
                                                    <button
                                                        type="button"
                                                        onClick={() => removeRecipient(index)}
                                                        className="text-red-600 hover:text-red-800"
                                                        disabled={isSubmitting}
                                                    >
                                                        <TrashIcon className="w-4 h-4" />
                                                    </button>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}
                                {errors.recipients && (
                                    <p className="mt-1 text-sm text-red-500">{errors.recipients}</p>
                                )}
                            </div>

                            {/* Description - Full width */}
                            <div className="col-span-1 md:col-span-2">
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Description
                                </label>
                                <textarea
                                    name="description"
                                    value={formData.description}
                                    onChange={handleChange}
                                    rows="3"
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                                    placeholder="Enter document description"
                                    disabled={isSubmitting}
                                />
                            </div>

                            {/* Remarks - Full width */}
                            <div className="col-span-1 md:col-span-2">
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Remarks
                                </label>
                                <textarea
                                    name="remarks"
                                    value={formData.remarks}
                                    onChange={handleChange}
                                    rows="2"
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                                    placeholder="Enter any additional remarks"
                                    disabled={isSubmitting}
                                />
                            </div>
                        </div>

                        {/* Debug Log Button - Optional, remove in production */}
                        <div className="mt-4 flex justify-end space-x-2">
                            <button
                                type="button"
                                onClick={logCurrentFormData}
                                className="px-3 py-1 text-sm bg-gray-100 text-gray-700 rounded hover:bg-gray-200"
                                disabled={isSubmitting}
                            >
                                🔍 Log Form Data
                            </button>
                        </div>

                        {/* Form Actions */}
                        <div className="mt-6 px-6 py-4 border-t border-gray-200 flex justify-end space-x-3">
                            <button
                                type="button"
                                onClick={handleClose}
                                className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50"
                                disabled={isSubmitting}
                            >
                                Cancel
                            </button>
                            <button
                                type="submit"
                                className="px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
                                disabled={isSubmitting}
                            >
                                {isSubmitting ? 'Submitting...' : 'Submit Document'}
                            </button>
                        </div>

                        {showSuccess && (
                            <div className="fixed inset-0 z-50 flex items-center justify-center">
                                <div className="rounded-lg border border-green-400 bg-green-100 px-6 py-4 text-green-700">
                                    ✅ Document created successfully!
                                </div>
                            </div>
                        )}

                            {submittedDocument && (
                                <EmailStatusTracker
                                    document={submittedDocument}
                                    onClose={() => setSubmittedDocument(null)}
                                />
                            )}
                        
                    </form>
                </div>
            </div>
        </div>
    );
}